platform:
  - x64
install:
  - ps: Start-FileDownload 'http://static.rust-lang.org/dist/rust-1.8.0-x86_64-pc-windows-gnu.exe'
  - rust-1.8.0-x86_64-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc --version
  - cargo --version

build: false

test_script:
  - cargo test --verbose
  - cargo build --release
  - target\release\hs.exe -v
