[package]
name = "heatseeker"
version = "1.3.0"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
build = "build.rs"

[[bin]]
name = "hs"

[dependencies]
getopts = "*"
unicode-width = "*"

[build-dependencies]
time = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"

[features]
nightly = []
