[package]
name = "heatseeker"
version = "1.4.0"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
build = "build.rs"

[[bin]]
name = "hs"

[dependencies]
libc = "0.2.12"
getopts = "0.2.14"
unicode-width = "0.1.3"

[build-dependencies]
time = "0.1.35"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.7"
kernel32-sys = "0.2.2"

[features]
nightly = []
