[package]
name = "heatseeker"
version = "0.0.1"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]

[[bin]]
name = "hs"

[dependencies]
getopts = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"
