[package]
name = "heatseeker"
version = "1.4.0"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
build = "build.rs"

[[bin]]
name = "hs"

[dependencies]
libc = "0.2.10"
getopts = "0.2.14"
unicode-width = "0.1.3"

[build-dependencies]
time = "0.1.35"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2.6"
kernel32-sys = "0.2.2"

[features]
nightly = []
