[package]
name = "selectric"
version = "0.0.1"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]

[dependencies]
getopts = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"
