[package]
name = "heatseeker"
version = "1.5.0"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
build = "build.rs"

[[bin]]
name = "hs"

[dependencies]
libc = "0.2.15"
getopts = "0.2.14"
unicode-width = "0.1.3"
num_cpus = "1.0.0"
crossbeam = "0.2.10"

[build-dependencies]
time = "0.1.35"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.2"