[package]
name = "heatseeker"
version = "0.3.0"
authors = ["Ryan Schmitt <rschmitt@pobox.com>"]
build = "build.rs"

[[bin]]
name = "hs"

[dependencies]
getopts = "*"
unicode-width = "0.1.1"
num_cpus = "0.2.2"

[build-dependencies]
time = "*"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "*"
kernel32-sys = "*"
